### ISSUE TITLE
Cannot setup connection

### ISSUE THREAD

**Issue by webmechanics** [redis/RedisDesktopManager#1847]
Trying to setup connection via SSH Tunnel, I fill host, port and user fields, and get this error http://cl.ly/image/1e0b1U0j352X. I tried to change IP address to hostname, check "password" checkbox - it doesnt help

**Comment by uglide** [comment]
Fixed in 0.7.7

**Comment by webmechanics** [comment]
thank! where I can download 0.7.7? it still 0.7.6 on a website...

**Comment by uglide** [comment]
Hi, I will inform you as soon as Release Candidate is ready.

**Comment by uglide** [comment]
@webmechanics 
Please download this night build http://redisdesktop.com/builds/redis-desktop-manager-0.7.7.30.dmg

**Comment by czerasz** [comment]
Hi, I can still experience connection issues while using the internal "SSH Tunnel" option in version `0.8.3-120`. The problem is well described [here](http://unix.stackexchange.com/questions/199226/why-ssh-login-works-in-shell-but-fails-in-all-third-parties-via-ssh-tunnel).

System Information:

| Field | Value |
| --- | --- |
| Description | Ubuntu 15.10 |
| Release | 15.10 |
| Codename | wily |

**Comment by Alexand** [comment]
Hi Guys, I also experience the same issue. I'm using version `0.8.3-2550` on `OS X 10.11.4`

**Comment by GSailen** [comment]
Same issue here, version 0.8.3-2550 on OS X 10.13.4

**Comment by uglide** [comment]
0.8.3-2550 is 3 years old release. Please upgrade to latest version (0.9.3).
